name: Android Resources Diagnostic

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  resources-diagnostic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android platform and build-tools
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Configure Build Properties
        run: |
          echo "CLIENT_ID=${{ secrets.CLIENT_ID || 'PLACEHOLDER' }}" >> local.properties
          echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET || 'PLACEHOLDER' }}" >> local.properties

      - name: Print Android SDK info
        run: |
          echo "ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT}"
          sdkmanager --list | head -n 100
          ls -la "${ANDROID_SDK_ROOT}/platforms/android-35" || true

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Print Gradle project properties (compileSdk)
        run: ./gradlew :app:properties | grep -i "compileSdk" || true

      - name: Grep '{str}' in app resources
        run: |
          echo "Scanning app/src/main/res for >{str}< ..."
          if grep -R --line-number '>{str}<' app/src/main/res; then
            echo "Found raw {str} placeholders in app resources (needs fix)."
          else
            echo "No raw {str} found in app resources."
          fi

      - name: Grep '{str}' in Gradle transformed values (best-effort, may be large)
        run: |
          echo "Scanning Gradle caches for library values containing {str} (this can be large)..."
          grep -R --line-number "{str}" ~/.gradle/caches 2>/dev/null | head -n 200 || true

      - name: Merge resources (release) with --debug and --stacktrace
        run: ./gradlew :app:mergeReleaseResources --debug --stacktrace

      - name: List merged values files (diagnostic)
        if: always()
        run: |
          echo "Searching for merged 'values.xml' files under app/build (merged.dir / merged_res / incremental)..."
          echo "--- find matches ---"
          # common locations used by different Gradle/AGP versions
          find app/build -type f -name values.xml -path "*merged.dir*" -print || true
          find app/build -type f -path "*/merged.dir/*/values*/values.xml" -print || true
          find app/build -type f -path "*/merged_res/*/values*/values.xml" -print || true
          find app/build -type f -name values.xml -path "*/merge*/merge*/merged.dir/*" -print || true
          echo "--- list directories around matches ---"
          # list parent directories for easier debugging in the logs
          find app/build -type f -name values.xml -path "*merged.dir*" -exec dirname {} \; | sort -u || true
          echo "Done listing. (If nothing printed above, the merged values files were not produced at the expected locations.)"

      - name: Collect merged values into a deterministic folder (for upload)
        if: always()
        run: |
          echo "Preparing merged-values/ directory for upload..."
          rm -rf merged-values
          mkdir -p merged-values/values

          # try multiple common patterns (AGP/Gradle variations). Copy any found values.xml into merged-values/values/
          echo "Searching common AGP output locations and copying found values.xml into merged-values/values/ ..."
          set -o pipefail || true
          find app/build -type f -name values.xml \
            -path "*/merged.dir/*/values*/values.xml" -o \
            -path "*/merged_res/*/values*/values.xml" -o \
            -path "*/intermediates/**/merged.dir/*/values*/values.xml" -o \
            -path "*/merge*/merge*/merged.dir/*/values*/values.xml" -o \
            -path "*/outputs/*/values*/values.xml" \
            -print 2>/dev/null | while read -r f; do
              echo " -> found: $f"
              # create unique filename to avoid collisions (use path-safe replacement)
              safe=$(echo "$f" | tr '/' '_' | sed 's/[^A-Za-z0-9_.-]/_/g')
              cp -v "$f" "merged-values/values/${safe}"
            done || true

          # Also try some looser globs (best-effort)
          shopt -s nullglob 2>/dev/null || true
          for g in app/build/**/values*/values.xml app/build/**/merged_res/**/values*/values.xml app/build/**/intermediates/**/values*/values.xml; do
            for f in $g; do
              if [ -f "$f" ]; then
                echo " -> found (glob): $f"
                safe=$(echo "$f" | tr '/' '_' | sed 's/[^A-Za-z0-9_.-]/_/g')
                cp -v "$f" "merged-values/values/${safe}"
              fi
            done
          done

          echo "Final contents of merged-values/values/:"
          ls -la merged-values/values || true

      - name: Upload merged values (release)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: merged-values-${{ github.sha }}
          # Upload the deterministic folder we created; this guarantees the artifact will contain files if any were found.
          path: |
            merged-values/**
            # keep the original globs as fallback (ignored if no files)
            app/build/**/merged.dir/**/values*/values.xml
            app/build/**/merged_res/**/values*/values.xml
            app/build/**/merge**Resources/**/merged.dir/**/values*/values.xml
            app/build/**/intermediates/**/merged.dir/**/values*/values.xml
          if-no-files-found: warn
          retention-days: 7
          compression-level: 6
          overwrite: false
          include-hidden-files: false

      - name: Upload Gradle daemon/build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-logs-${{ github.sha }}
          path: |
            ~/.gradle/daemon/*/daemon-*.out.log
            **/build/outputs/logs/**
            merge-debug.log
          if-no-files-found: ignore
          retention-days: 7